### ISSUE TITLE
missing apiobjects on main branch

### ISSUE THREAD

**Issue by snowsky** [freetocompute/kebe#6]
Hi there,

I run into the below error message when I tried to start the service. It seems the folder is not in this repo.

```
$ go run bin/admin/main.go store -s xxx -p xxx -d xxx -x xxx -u xxx -m xxx -a xxx -k xxx initialize
cmd/admin/accounts/accounts.go:7:2: no required module provides package github.com/freetocompute/kebe/pkg/kebe/apiobjects; to add it:
	go get github.com/freetocompute/kebe/pkg/kebe/apiobjects
```

Thanks!

**Comment by futuretim** [comment]
Hi! Welcome. That is part of an older API / interface that will eventually be in place for store administration but it was not ready. I will add it back as needed and my next big push should have it properly removed and a lot more functionality (hopefully this weekend). In the meantime if you like I have hopefully added enough back here: https://github.com/freetocompute/kebe/tree/old_kebe_api. So just please switch branches! Thanks!

**Comment by futuretim** [comment]
I also created a dev branch and added all of my work currently. That would be a better thing to test / look at for now.
